app:
  build: .
  links:
   - db
  ports:
   - "8080:8080" # change to whatever port is to be used
  environment:
   - NODE_ENV=development # production for staging
db:
  image: mongo
  ports:
   - "27017:27017"